language: python
env:
  - CODECOV_TOKEN=""
python:
  - "3.6"
install:
  - pip install .
  - pip install -r $PWD/requirements.txt
  - pip install nose codecov coverage
script:
  - nosetests --with-coverage
after_success:
  - codecov -t $CODECOV_TOKEN
  -
