language: python
env:
  - CODECOV_TOKEN="9167fe5e-40c3-42a9-a830-ffa468fbd660"
python:
  - "3.6"
install:
  - pip install .
  - pip install -r $PWD/requirements.txt
  - pip install nose codecov coverage
script:
  - nosetests --with-coverage
after_success:
  - codecov -t $CODECOV_TOKEN

